theme: "anubis"
baseUrl: "https://nkthanh.dev"
DefaultContentLanguage: "vi"
paginate: 10
googleAnalytics: ""
enableRobotsTXT: true

languages:
  vi:
    title: "Nguyễn Khắc Thành"
    params:
      author: "Nguyễn Khắc Thành"
      description: ""
      dateFormat: "02-01-2006"
    menu:
      main:
      - identifier: post
        name: Bài viết
        url: /posts
        weight: 2
      - identifier: about
        name: Giới thiệu
        url: /about
        weight: 1
      - identifier: tags
        name: Thẻ
        url: /tags
        weight: 0
    contentDir: content/vi
    languageCode: "vi-vn"
    languageName: Tiếng Việt
    weight: 1

  en:
    title: "Nguyen Khac Thanh"
    params:
      author: "Nguyen Khac Thanh"
      description: ""
      dateFormat: "2006-01-02"
    menu:
      main:
      - identifier: post
        name: Post
        title: Post
        url: /posts
        weight: 2
      - identifier: about
        name: About
        url: /about
        weight: 1
      - identifier: tags
        name: Tags
        url: /tags
        weight: 0
    contentDir: content/en
    languageCode: "en-us"
    languageName: English
    weight: 2

params:
  math: true
  paginationSinglePost: true
  style: light-with-switcher
  readMore: false
  utterancesRepo: magiskboy/
  Firebase:
    ProjectId: myblog-e552f
    ApiKey: AIzaSyAny8MQuh4uEziV2FsJAEBMHvRcCjHeDj0
    DatabaseURL: https://myblog-e552f-default-rtdb.firebaseio.com
    StorageBucket: myblog-e552f.appspot.com
    SenderId: 488762331302
    AppId: 1:488762331302:web:8edebcb8c2116cff0b2467
    AuthDomain: myblog-e552f.firebaseapp.com
    MeasurementId: G-WVWZEJLY14

markup:
  goldmark:
    renderer:
      unsafe: true # disable raw HTML in Markdown

taxonomies:
  category: categories
  tag: tags

PygmentsStyle: "github"

enableEmoji: true
